ALTER TABLE events
    ADD COLUMN archived BOOLEAN DEFAULT FALSE;

ALTER TABLE venues
    ADD COLUMN updated_at TIMESTAMP DEFAULT NOW();
ALTER TABLE events
    ADD COLUMN updated_at TIMESTAMP DEFAULT NOW();